<?php
	if(is_single('custom01')):
		include_once('wc_item_single_custombag.php');
	elseif(is_single('custom02')):
		include_once('wc_item_single_disney.php');
	elseif(is_single('marty-heart')):
		include_once('wc_item_single_martyheart.php');
	elseif(is_single('marty-ribon')):
		include_once('wc_item_single_martyribon.php');
	elseif(is_single('marty-flower')):
		include_once('wc_item_single_martyflower.php');
	elseif(is_single('marty-animal')):
		include_once('wc_item_single_martyanimal.php');
	else:
		include_once('wc_item_single_default.php');
	endif;
?>
